# Generated by Django 5.0.7 on 2024-08-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reject_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
