# Generated by Django 5.0.7 on 2024-08-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_submission_error_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuefield',
            name='type',
            field=models.IntegerField(choices=[(1, 'Integer'), (2, 'String'), (3, 'Integer Array'), (4, 'String Array'), (5, '2D Integer Array'), (6, '2D String Array'), (7, 'Boolean')]),
        ),
    ]
