# Generated by Django 5.0.7 on 2024-09-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuefield',
            name='type',
            field=models.IntegerField(choices=[(1, 'Integer'), (2, 'String'), (3, 'Integer Array'), (4, 'String Array'), (5, '2D Integer Array'), (6, '2D String Array'), (7, 'Boolean'), (8, 'Float')]),
        ),
    ]
