# Generated by Django 5.0.7 on 2024-09-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_valuefield_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
