# Generated by Django 5.0.7 on 2024-07-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsolvedproblems',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem', to_field='public_id'),
        ),
        migrations.AddField(
            model_name='account',
            name='solved_problems',
            field=models.ManyToManyField(through='accounts.AccountSolvedProblems', to='problems.problem'),
        ),
    ]
