# Generated by Django 5.0.7 on 2024-08-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='login_type',
            field=models.IntegerField(choices=[(0, 'Email'), (1, 'Google')], default=0),
        ),
    ]
