# Generated by Django 5.0.7 on 2024-08-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_first_name_account_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='max_streak',
            field=models.IntegerField(default=0),
        ),
    ]
